export const HOST = process.env.NEXT_PUBLIC_SERVER_URL;
export const API_URL = `${HOST}/api`;
export const AUTH_ROUTES = `${API_URL}/auth`; // Movido para cima
export const GET_USER_INFO = `${AUTH_ROUTES}/get-user-info`;
export const SET_USER_INFO = `${AUTH_ROUTES}/set-user-info`;
export const SIGNUP_ROUTE = `${AUTH_ROUTES}/signup`;
export const LOGIN_ROUTE = `${AUTH_ROUTES}/login`;
export const GIG_ROUTES = `${API_URL}/gigs`; // Corrigido para API_URL
export const ADD_GIG_ROUTE = `${GIG_ROUTES}/add`;
export const GET_USER_GIGS_ROUTE = `${GIG_ROUTES}/get-user-gigs`;
export const EDIT_GIG_DATA = `${GIG_ROUTES}/edit-gig`;
export const SEARCH_GIGS_ROUTE = `${GIG_ROUTES}/search-gigs`;
export const GET_GIG_DATA = `${GIG_ROUTES}/get-gig-data`;
export const SET_USER_IMAGE = `${AUTH_ROUTES}/set-user-image`;
