export const reducerCases = {
    SET_USER: "SET_USER",
    TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
    TOGGLE_SIGNUP_MODAL: "TOGGLE_SIGNUP_MODAL",
    CLOSE_AUTH_MODAL: "CLOSE_AUTH_MODAL",
    SWITCH_MODE: "SWITCH_MODE",
    SET_GIG_DATA: "SET_GIG_DATA",
};